name: 'Fetch Superset Community Stats'
description: 'An action to fetch various stats related to the Superset project and publish them to be consumed by the Superset Community Dashboard.'
inputs:
  token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run fetch script
      run: |
        python fetch_asf_repo_stats.py
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
